# Generated by Django 4.1 on 2022-08-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeid', models.CharField(max_length=11)),
                ('DOJ', models.CharField(max_length=10)),
                ('SeatNumber', models.CharField(max_length=10)),
                ('SeatStatus', models.CharField(blank=True, max_length=10)),
                ('seatprice', models.CharField(max_length=10)),
                ('Discount_amount', models.CharField(max_length=10)),
                ('Xcoordinate', models.CharField(max_length=10, null=True)),
                ('Ycoordinate', models.CharField(max_length=10, null=True)),
                ('Zcoordinate', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'booking_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeid', models.CharField(max_length=15)),
                ('DOJ', models.CharField(max_length=10)),
                ('operatorId', models.CharField(max_length=10)),
                ('operatorName', models.CharField(max_length=50)),
                ('DepartureTime', models.CharField(max_length=25)),
                ('arriveTime', models.CharField(max_length=25)),
                ('BusType', models.CharField(max_length=25)),
                ('rating', models.CharField(max_length=5)),
                ('rating_count', models.CharField(max_length=20, null=True)),
                ('is_sleeper', models.BooleanField(null=True)),
                ('is_AC', models.BooleanField(null=True)),
                ('available_seats', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'route_new',
                'managed': False,
            },
        ),
    ]
