# Generated by Django 4.1 on 2022-08-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking_new',
            options={},
        ),
        migrations.AlterModelOptions(
            name='route_new',
            options={},
        ),
    ]
