# Generated by Django 4.1 on 2022-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_booking_new_options_alter_route_new_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route_new',
            name='id',
        ),
        migrations.AlterField(
            model_name='route_new',
            name='routeid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
